export const surpriseMe = [
  "a painting of a fox in the style of Starry Night",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "an expressive oil painting of a basketball player dunking, depicted as an explosion of a nebula",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "an armchair in the shape of an avocado",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "3D render of a small pink balloon dog in a light pink room",
  "an astronaut playing basketball with cats in space, digital art",
  "teddy bears shopping for groceries, one-line drawing",
  "a cat submarine chimera, digital art",
  "a stained glass window depicting a hamburger and french fries",
  "photograph of an astronaut riding a horse",
  "a bowl of soup that is also a portal to another dimension, digital art",
  "a stern-looking owl dressed as a librarian, digital art",
  "'a sea otter with a pearl earring' by Johannes Vermeer",
];
